#build stage
FROM node:18-alpine AS builder

#setting a directory for app
WORKDIR /app

#copying dependencies 
COPY package*.json ./

#installing pacakages
RUN npm install

#copying project
COPY . .

#build dist folder
RUN npm run build  # Creates dist/angular-15-crud/



#final stage
FROM nginx:alpine

#copying dist folder from build stage
COPY --from=builder /app/dist/angular-15-crud /usr/share/nginx/html

#nginx set up to connect backend
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

#app listens on this port
EXPOSE 80