# Build 
FROM node:18-alpine AS build

#setting up working directory 
WORKDIR /usr/src/app

#copying dependencies 
COPY package.json .

#install and update dependencies
RUN npm install

#copying entire project
COPY . .

#setting port for the application
EXPOSE 3000

# running application
CMD ["npm", "start"]